apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      initContainers:
        - name: wait-for-mongodb-service
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 120); do nc -zvw1 mongo-statistics 27017 && exit 0 || sleep 5; done; exit 1"]
      containers:
        - name: statistics-container
          image: akstestacrr.azurecr.io/azure-statistics-microservice:v1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_CONFIG_LOCATION
              value: file:/resources-config/application.yml,file:/resources-config/statistic.yml
          envFrom:
            - secretRef:
                name: statistics-service
            - secretRef:
                name: mongodb-credentials
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 300Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /statistics/actuator/info
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /statistics/actuator/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: configmap-statistics-volume
              mountPath: /resources-config
      volumes:
        - name: configmap-statistics-volume
          configMap:
            name: configmap-statistic
---
apiVersion: v1
kind: Service
metadata:
  name: statistic
spec:
  selector:
    app: statistics
  ports:
    - port: 80
      targetPort: 80