app:
  auth-service: localhost
  statistics-service-host: localhost
  statistics-service-port: 8081

security:
  oauth2:
    resource:
      user-info-uri: "http://${app.auth-service}:5000/uaa/users/current"

---
spring:
  config:
    activate:
      on-profile: prod

app:
  auth-service: authorization
  auth-server-port: 80
  statistics-service-host: statistic
  statistics-service-port: 80

security:
  oauth2:
    resource:
      user-info-uri: "http://${app.auth-service}:${app.auth-server-port}/uaa/users/current"

