app:
  auth-service: localhost
  statistics-service-host: localhost
  statistics-service-port: 8081

security:
  oauth2:
    resource:
      user-info-uri: "http://${app.auth-service}:5000/uaa/users/current"

---
spring:
  config:
    activate:
      on-profile: docker-compose

app:
  registry: registry
  auth-service: auth-server
  auth-server-port: 5000
  statistics-service-host: statistics-service
  statistics-service-port: 80

---
spring:
  config:
    activate:
      on-profile: prod

app:
  auth-service: authorization
  auth-server-port: 80
  statistics-service-host: statistic
  statistics-service-port: 80

