apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics
spec:
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - name: statistics-container
          image: acrekstest.azurecr.io/azure-statistics-microservice:8f23043
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "350Mi"